tap "felixkratz/formulae"
tap "git-mastery/gitmastery"
tap "nikitabobko/tap"
tap "theboredteam/boring-notch"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Emacs dependency management
brew "cask"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Multi-platform library for OpenGL applications
brew "glfw"
# Simple terminal UI for git commands
brew "lazygit"
# Minimalist GNU for Windows and GCC cross-compilers
brew "mingw-w64"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# File browser
brew "ranger"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Programmatically correct mistyped console commands
brew "thefuck"
# Terminal multiplexer
brew "tmux"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# A window border system for macOS
brew "felixkratz/formulae/borders"
# CLI tool for Git-Mastery
brew "git-mastery/gitmastery/gitmastery"
# AeroSpace is an i3-like tiling window manager for macOS
cask "nikitabobko/tap/aerospace"
# GPU-accelerated terminal emulator
cask "alacritty"
# Web browser focusing on privacy
cask "brave-browser"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
# Menu bar manager
cask "jordanbaird-ice"
# Open-source keystroke visualiser
cask "keycastr"
# Open-source cross-platform alternative to AirDrop
cask "localsend"
# Lunar calendar for menu bar
cask "lunarbar"
# Replacement for Docker Desktop
cask "orbstack"
vscode "ajshort.include-autocomplete"
vscode "davidanson.vscode-markdownlint"
vscode "eamodio.gitlens"
vscode "formulahendry.code-runner"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "hoovercj.vscode-power-mode"
vscode "kdarkhan.mips"
vscode "marp-team.marp-vscode"
vscode "maximetinu.identical-sublime-monokai-csharp-theme-colorizer"
vscode "mechatroner.rainbow-csv"
vscode "mkxml.vscode-filesize"
vscode "ms-ceintl.vscode-language-pack-zh-hans"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.remote-explorer"
vscode "pkief.material-icon-theme"
vscode "redhat.java"
vscode "tamasfe.even-better-toml"
vscode "tomoki1207.pdf"
vscode "twxs.cmake"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscodevim.vim"
vscode "yltx.vscode-luogu"
vscode "yzhang.markdown-all-in-one"
